notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install -U tox-travis
deploy:
  provider: pypi
  user: ddaa
  password:
    secure: "Jt1K3/vc/VPl1WVlkU7aGZByd6Nk8XhB3W/mOeBOB6JdozGbTaTyZPiKz9xiL7juWesNFMhvZQ8u0eT1fkCK9+/IsnB77jSgSYbGW0UFDHIFciLwuus8J+AZvo9iozM8+nCl6wfh+TBK1Gl8vsSpfrV1lysP/45Fml38aHCeSOFcaRkI+mxZskppANNowGzL7VqnbWIKRohZfOT0yUgt2BToOucDORsiEdtL/jvPZaj2WmIaAoPKn+xF35aLQ45TN5gjjg6UuN80F9SBZl08Di6uNvlKE04T+7UC/EW00ZwBqV5utBRmFi91+IJXcJMwTHl70NezP57d8rChJMc4X1LGGW4/r2f31OMK9w9FCn6KRzMNvp5EmxO/vOobde1a3mg3Agpxn1JdNpnmcyETI099XaHlxhbgL+a6sMejKEqS+9y9gLvS6I5KmJgawJ7KSampPZchyt/4v/XWZfeNJOT0Sb34bED+nNcW1V1nUaEB0/erDEqfTzN7nIJWdElKZmGCq/kkkluwiQTu0dWd0Ec2fn2DKAmYBp7lVVH7dljtd/cV56KbqEe+oeyM60WZOff+ZKwV+dMhCGsf1LX6Sqb8fG7xUA/gZNrn2wiDVDUGdtSLUDTYVCAn8MecujVdNjw8mGed55o3px8Hp+uTKRkCSWQg8FGA+yhKEZ21cGM="
  on:
    tags: true
    branch: master
    repo: DiogoAndre/acl_stats
    python: 3.6
script:
- tox
